-- Добавление данных о стендап-шоу 21 сентября
-- Сначала создаем запись с фиксированным UUID
INSERT INTO stream_settings (
  id,
  title,
  description,
  dacast_content_id,
  dacast_embed_url,
  dacast_rtmp_url,
  dacast_stream_key,
  price,
  currency,
  stream_start_time,
  stream_end_time,
  poster_url,
  is_live,
  is_active,
  max_concurrent_viewers,
  created_at,
  updated_at
) VALUES (
  '550e8400-e29b-41d4-a716-446655440000'::uuid,
  'Стендап Вечер',
  'Присоединяйтесь к незабываемому вечеру смеха! Наши талантливые комики представят лучшие номера стендап-комедии. Вечер полон юмора, остроумия и отличного настроения. Не упустите возможность провести время в компании единомышленников и зарядиться позитивом на всю неделю!',
  NULL,
  NULL,
  NULL,
  NULL,
  150,
  'MDL',
  '2024-09-21 20:00:00+00',
  '2024-09-21 22:00:00+00',
  '/IMG_0090.png.webp',
  false,
  true,
  500,
  NOW(),
  NOW()
) ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  description = EXCLUDED.description,
  dacast_content_id = EXCLUDED.dacast_content_id,
  dacast_embed_url = EXCLUDED.dacast_embed_url,
  dacast_rtmp_url = EXCLUDED.dacast_rtmp_url,
  dacast_stream_key = EXCLUDED.dacast_stream_key,
  price = EXCLUDED.price,
  currency = EXCLUDED.currency,
  stream_start_time = EXCLUDED.stream_start_time,
  stream_end_time = EXCLUDED.stream_end_time,
  poster_url = EXCLUDED.poster_url,
  is_live = EXCLUDED.is_live,
  is_active = EXCLUDED.is_active,
  max_concurrent_viewers = EXCLUDED.max_concurrent_viewers,
  updated_at = NOW();